version: '3.8'

services:
  web:
    image: 051826698008.dkr.ecr.us-east-1.amazonaws.com/financial_app:${IMAGE_TAG}  
    command: gunicorn financial_app.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=your_db_name
      - DB_USER=your_db_user
      - DB_PASSWORD=your_db_password

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=your_db_name
      - POSTGRES_USER=your_db_user
      - POSTGRES_PASSWORD=your_db_password
    ports:
      - "5432:5432"

volumes:
  postgres_data:
