# Generated by Django 3.2.25 on 2024-10-20 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_fetcher', '0002_stockprediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='close_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='high_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='low_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='open_price',
            field=models.FloatField(),
        ),
    ]
